---
version: "2"
services:
  sxo_sidecar:
    build: "."
    environment:
      - "FLASK_ENV=development"
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "5000:5000"
    command: python3 server.py
    depends_on:
      - redis

  worker:
    build: "."
    command: celery -A server.celery worker --loglevel=info  --concurrency=50
    environment:
      - "FLASK_ENV=development"
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      - sxo_sidecar
      - redis
  
  flower:  
    image: mher/flower:0.9.7
    command: ["flower", "--broker=redis://redis:6379/0", "--port=5555"]  
    ports:  
      - 5555:5555 
    depends_on:
      - worker
      - redis
  
  redis:
    image: redis:6-alpine  
